---
title: Configure Updates -> Drivers
description: Configure Windows Update settings for device drivers
privilege: TrustedInstaller
actions:

  # === Do not include drivers with Windows Updates (native implementation)
  # ------> Driver updates can still be installed manually via Device Manager
  # ------> or the manufacturer's software.
  # ------> https://admx.help/?Category=WindowsUpdate_2019&Policy=Microsoft.Policies.WindowsUpdate::ExcludeWUDriversInQualityUpdate
 - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'
    value: 'ExcludeWUDriversInQualityUpdate'
    type: REG_DWORD
    data: '1'
