[Theme]
DisplayName=EBOS Frost
ThemeId={E75B49FC-5543-4220-9787-0B0F851DFD1A}

[Control Panel\Desktop]
Wallpaper=%windir%\EBOSModules\Wallpapers\ebos-v0.4.x-light.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[Control Panel\Cursors]
AppStarting=%windir%\cursors\aero_working.ani
Arrow=%windir%\cursors\aero_arrow.cur
Hand=%windir%\cursors\aero_link.cur
Help=%windir%\cursors\aero_helpsel.cur
No=%windir%\cursors\aero_unavail.cur
NWPen=%windir%\cursors\aero_pen.cur
SizeAll=%windir%\cursors\aero_move.cur
SizeNESW=%windir%\cursors\aero_nesw.cur
SizeNS=%windir%\cursors\aero_ns.cur
SizeNWSE=%windir%\cursors\aero_nwse.cur
SizeWE=%windir%\cursors\aero_ew.cur
UpArrow=%windir%\cursors\aero_up.cur
Wait=%windir%\cursors\aero_busy.ani
DefaultValue=Windows Default

[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%windir%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC4B8D8B6
SystemMode=Dark
AppMode=Light
VisualStyleVersion=10

[MasterThemeSelector]
MTSM=RJSPBS
