[Theme]
DisplayName=EBOS Core
ThemeId={36D86FC8-56D6-4642-8B09-337032B762B5}

[Control Panel\Desktop]
Wallpaper=%windir%\EBOSModules\Wallpapers\ebos-solid.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[Control Panel\Cursors]
AppStarting=%windir%\cursors\aero_working.ani
Arrow=%windir%\cursors\aero_arrow.cur
Hand=%windir%\cursors\aero_link.cur
Help=%windir%\cursors\aero_helpsel.cur
No=%windir%\cursors\aero_unavail.cur
NWPen=%windir%\cursors\aero_pen.cur
SizeAll=%windir%\cursors\aero_move.cur
SizeNESW=%windir%\cursors\aero_nesw.cur
SizeNS=%windir%\cursors\aero_ns.cur
SizeNWSE=%windir%\cursors\aero_nwse.cur
SizeWE=%windir%\cursors\aero_ew.cur
UpArrow=%windir%\cursors\aero_up.cur
Wait=%windir%\cursors\aero_busy.ani
DefaultValue=Windows Default

[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC428593E
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[MasterThemeSelector]
MTSM=RJSPBS
