---
title: ReviOS Integration
description: Applies integrated ReviOS tasks before EBOS
privilege: Admin
actions:
  # ReviOS Integration — Applies integrated ReviOS tasks before EBOS.
  # EBOS runs afterward and has priority for any overlapping settings.

  - !task: { path: 'revios\Tasks\start.yml' }

  - !task: { path: 'revios\Tasks\packages\app-win32.yml' }
  # Uninstalling WinSxS packages before app-win32 could leave leftovers
  - !task: { path: 'revios\Tasks\packages\win-sxs.yml' }
  - !task: { path: 'revios\Tasks\packages\appx.yml' }

  - !task: { path: 'revios\Tasks\software.yml' }
  - !task: { path: 'revios\Tasks\services.yml' }

  - !task: { path: 'revios\Tasks\registry.yml' }
  - !task: { path: 'revios\Tasks\revert.yml' }
  - !task: { path: 'revios\Tasks\final.yml' }
